version: "3.8"

services:
  ingestion-service:
    build:
      context: .
    ports:
      - "8000:8000"  # Expose FastAPI service on port 8000
    environment:
      - KAFKA_BROKER=localhost:9092  # Address of your Kafka server
      - KAFKA_TOPIC=raw_device_data  # Topic to send events to
